config/routes.rb
Estagio::Application.routes.draw do

  

  

scope 'estagios/' do

resources :cancelamentos
resources :aprovas
resources :docentes
resources :fluxomatriculas
      
    devise_for :usuarios, :controllers => { :registrations => "registrations" } do
    get 'logout' => 'sessions#destroy', :as => :destroy_user_session
    get 'login' => 'devise/sessions#new'
  end
      match 'home', :controller => 'avisos', :action => 'home'
      match'/confirm', :controller => 'avisos', :action => 'confirm'

    
      match '/cadastro', :controller => 'matriculas', :action => 'cadastro'
      match '/cadastro/create', :controller => 'matriculas', :action => 'create'
      match '/cadastro/filtro', :controller => 'matriculas', :action => 'filtro'
    
      match '/email/matriculas', :controller => 'matriculas', :action => 'email_matriculas'
      
      match '/matriculas/detalhes/:id', :controller => 'matriculas', :action => 'detalhes'
      match '/matriculas/analise/:id', :controller => 'matriculas', :action => 'analise'
      match '/matriculas/anexo/:id', :controller => 'matriculas', :action => 'anexo'
      match '/matriculas/download/:id', :controller => 'matriculas', :action => 'download'
      
      match '/delete/disciplina/', :controller => 'disciplinas', :action => 'delete'
      match 'delete/aviso', :controller => 'avisos', :action => 'delete'
      match 'delete/periodo', :controller => 'periodos', :action => 'delete'
      
      match 'users/', :controller => 'users', :action => 'index'
      match 'users/edit', :controller => 'users', :action => 'edit'
      match 'users/update/:id', :controller => 'users', :action => 'update'
      match 'user/:id', :controller => 'users', :action => 'show'
      match '/teste',:controller => 'conceitos', :action => 'dssi.xls',:format => 'xls'
      match "relatorios/", :controller => 'relatorios', :action => 'index'
      match "relatorios/show/:id", :controller => 'relatorios', :action => 'show'
      match "relatorios/view/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'view', :format => 'pdf'
      match "relatorios/envio/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'envio'
      match "relatorios/detalhes/:periodo/:aluno_id/", :controller => 'relatorios', :action => 'detalhes'
      match '/testando',:controller=>'relatorios',:action=>'geral',:format=>'pdf'
      match "/cancelamento", :controller => 'cancelamentos', :action => 'inicio'
      match "/cancelamentos/new", :controller => 'cancelamentos', :action => 'show'
	  match "/cancelamentos/testo/:id", :controller=>'cancelamentos', :action=>'edit'
      match "conceitos/", :controller => 'conceitos', :action => 'index'
      match "conceitos/show/:id", :controller => 'conceitos', :action => 'show'
      match "conceitos/envio/:id", :controller => 'conceitos', :action => 'envio'
      match "conceitos/modelo/:curso/:periodo", :controller => 'conceitos', :action => 'modelo_email'      
      match "conceitos/dssi/:periodo/:ci.xls", :controller => 'conceitos', :action => 'dssi', :format => 'xls'
      match "conceitos/relatorio/:curso/:periodo", :controller => 'conceitos', :action => 'relatorio', :format => 'pdf'
      match "te",:controller => 'relatorios', :action => 'geral', :format => 'pdf'
	  match "/aprova", :controller => 'aprovas', :action=> 'index'
      match "/aprova/edit/:id", :controller => 'aprovas', :action=> 'edit'
      match "/aprova/new/:id", :controller => 'aprovas', :action=> 'new'
      
      match "/unificado/envio2/:id",:controller => 'relatorios', :action => 'envio2'
      match "/unificado/:centro/:id",:controller => 'relatorios', :action => 'unificado',:format=>'pdf'
	  
	  match "/dssirelatorio",:controller=>'dssirelatorios',:action=>'index'
      match "/dssirelatorios/:id", :controller=>'dssirelatorios',:action=>'show'
      match "/enviados/:id/:ci", :controller=>'dssirelatorios',:action=>'enviados',:format=>'pdf'
      
      match "/matricula/individual",:controller=>'matriculas',:action=>'individual'
      match "/matricula/individual/relindiv/:id",:controller=>'matriculas',:action=>'relindiv',:format=>'pdf'
      
      match "/docentes",:controller=>'docentes',:action=>'index'
	  
	  match "/fluxo",:controller=>'fluxomatriculas', :action=>'selecionadata'
      match "/fluxo/:periodo_id",:controller=>'fluxomatriculas', :action=>'selecionaaluno'
      match "/fluxo/:periodo_id/:aluno_id",:controller=>'fluxomatriculas', :action=>'fluxo',:format=>'pdf'

  

    	resources :cancelamentos
      resources :disciplinas
      resources :matriculas
      resources :periodos
	  
      
  root :to => 'avisos#index'

    
   resources :avisos
    
  end

end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  
  has_many :matriculas
  attr_accessible :codigo, :curso, :dia, :horario_fim, :horario_inicio, :nome, :turno,:docente
  
  validates_size_of :codigo, :is => 10
  validates :codigo, :curso, :presence => true
  validate :checa_horarios
  
  def checa_horarios
    if horario_inicio > horario_fim
      errors.add(:horario_inicio, :conflito_de_horarios_no_modelo)
    end    
  end
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  # GET /disciplinas
  # GET /disciplinas.json
  before_filter :authenticate_usuario!#, :except=>[:show]
  def index
    unless possui_acesso?()
      return
    end
    
    @periodo = Periodo.find(:last)
    unless @periodo.blank?
      # = "O período de cadastro/edição de disciplinas não está ativo ( "+@periodo.cadastro_inicio+" até "+@periodo.cadastro_fim
      @disciplinas = Disciplina.find(:all, :conditions => {:periodo_id => @periodo.id}, :order => "nome")
      @titulo = "Disciplinas ofertadas para o "+@periodo.quadrimestre.to_s+" de "+@periodo.ano.to_s+" pelo "+current_usuario.centro.to_s
    else
      @titulo = t(:semperiodo) #"Nenhum período cadastrado"
    end
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @disciplinas }
    end
  end

  # GET /disciplinas/1
  # GET /disciplinas/1.json
  def show
    unless possui_acesso?()
      return
    end
    @disciplina = Disciplina.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @disciplina }
    end
  end

  # GET /disciplinas/new
  # GET /disciplinas/new.json
  def new
    unless possui_acesso?()
      return
    end
    $docente_aux = Docente.find(:all,:conditions=>{:centro=>current_usuario.centro})
	@campo_vazio = Docente.new(:docente => "")
    $docente_aux.append(@campo_vazio)
    @disciplina = Disciplina.new
    
    if current_usuario.centro == "CMCC"
      $cursos = [[t(:lic_matematica)]]
      
    elsif current_usuario.centro == "CCNH"
      $cursos = [[t(:lic_ciencia_bio)],[t(:lic_filosofia)],[t(:lic_quimica)],[t(:lic_fisica)]]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @disciplina }
    end
  end

  # GET /disciplinas/1/edit
  def edit
    unless possui_acesso?()
      return
    end
    $docente_aux = Docente.find(:all,:conditions=>{:centro=>current_usuario.centro})
    @disciplina = Disciplina.find(params[:id])
    @matriculas = Matricula.find(:all, :conditions => {:disciplina_id => @disciplina.id})
    @campo_vazio = Docente.new(:docente => "")
    $docente_aux.append(@campo_vazio)
    if current_usuario.centro == "CMCC"
      $cursos = [[t(:lic_matematica)]]
      
    elsif current_usuario.centro == "CCNH"
      $cursos = [[t(:lic_ciencia_bio)],[t(:lic_filosofia)],[t(:lic_quimica)],[t(:lic_fisica)]]
    end
    
  end

  # POST /disciplinas
  # POST /disciplinas.json
  def create
    unless possui_acesso?()
      return
    end
    $docente_aux = Docente.find(:all,:conditions=>{:centro=>current_usuario.centro})
    @disciplina = Disciplina.new(params[:disciplina])
    @disciplina.periodo_id = Periodo.find(:last).id
@campo_vazio = Docente.new(:docente => "")
    $docente_aux.append(@campo_vazio)
    respond_to do |format|
      if @disciplina.save
        format.html { redirect_to @disciplina, notice: 'Disciplina criada com sucesso.' }
        format.json { render json: @disciplina, status: :created, location: @disciplina }
      else
        format.html { render action: "new" }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /disciplinas/1
  # PUT /disciplinas/1.json
  def update
    unless possui_acesso?()
      return
    end
    @disciplina = Disciplina.find(params[:id])

    respond_to do |format|
      if @disciplina.update_attributes(params[:disciplina])
        
        @matriculas = Matricula.find(:all, :conditions => {:disciplina_id => @disciplina.id})
        @matriculas.each do |matricula|
          #avisa aos alunos, caso existam, que houveram alterações na disciplina
          UserMailer.disciplina_editada(matricula).deliver
        end
        
        format.html { redirect_to @disciplina, notice: 'Disciplina atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplinas/1
  # DELETE /disciplinas/1.json
  def destroy
    unless possui_acesso?()
      return
    end
    @disciplina = Disciplina.find(params[:id])
    @disciplina.destroy

    respond_to do |format|
      format.html { redirect_to disciplinas_url }
      format.json { head :no_content }
    end
  end
  
    def delete
    unless possui_acesso?()
      return
    end
    @disciplina = Disciplina.find(params[:id])
    @disciplina.destroy

    respond_to do |format|
      format.html { redirect_to disciplinas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
  
  def filtro_centro(disciplina_id)
    #checa se a disciplina é do centro
    @retornar = false    
    @disciplina = Disciplina.find(disciplina_id)
    
    if current_usuario.centro == "CMCC"
      
        if @disciplina.curso == t(:lic_matematica) or @disciplina.curso == "CMCC" #"Licenciatura em matemática"            
            @retornar = true
        
        end
    elsif current_usuario.centro == "CCNH"
      
        if @disciplina.curso == t(:lic_ciencia_bio) or @disciplina.curso == t(:lic_fisica) or @disciplina.curso == t(:lic_quimica) or @disciplina.curso == t(:lic_filosofia) or @disciplina.curso == "CCNH" #Licenciatura em ciencias biologicas, física, química ou filosofia
            @retornar = true
        end

    end
    
    @retornar
  end
  def retorna_nome_doc(id)
    @docente=Docente.find(:first,:conditions=>{:docente=>id})
    @docente.docente
  end
  
  def concatena(id)
    @disciplina = Disciplina.find(id)
    @link = "localhost:3000/delete/disciplina"+@disciplina.id.to_string
  end
  
  def retorna_nome_aluno(aluno_id)
    @aluno = Usuario.find(aluno_id).nome
  end
  
  def retorna_email_aluno(aluno_id)
    @aluno = Usuario.find(aluno_id).email
  end  
  
  def retorna_telefone_aluno(aluno_id)
    @aluno = Usuario.find(aluno_id).telefone
  end   
end

app/views/disciplinas/_form.html.erb
<%= form_for(@disciplina) do |f| %>
  <% if @disciplina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disciplina.errors.count, "erro")%> detectado(s) nesse modelo:</h2>

      <ul>
      <% @disciplina.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :curso %><br />
    <%= f.select :curso, $cursos %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo, :size => 8 %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :turno %><br />
    <%= f.select :turno,[["Diurno"],["Noturno"]] %>
  </div>
  <div class="field">
    <%= f.label :dia %><br />
    <%= f.select :dia,[["2ª feira"],["3ª feira"],["4ª feira"],["5ª feira"],["6ª feira"],["sábado"]] %>
  </div>
  <div class="field">
    <%= f.label :horario_inicio %><br />
    <%= f.time_select :horario_inicio %>
  </div>
  <div class="field">
    <%= f.label :horario_fim %><br />
    <%= f.time_select :horario_fim %>
  </div>
<div class="field">
    <%= f.label :docente %><br />
    <%= f.select :docente, $docente_aux.collect{|m| [m.docente]}%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disciplinas/_matriculas.html.erb
<% if @matriculas.blank? %>
    <p>Nenhum aluno realizou matrícula nessa disciplina.</p>
    
<% else %>
    <p><b>Os seguintes alunos estão matriculados nessa disciplina</b></p>
    <table>
  <tr>
    <th>Aluno</th>
    <th>Email</th>
    <th>Telefone</th>
    <th></th>
  </tr>

<% @matriculas.each do |matricula| %>

  <tr>
    <td><%= retorna_nome_aluno(matricula.aluno_id)%></td>
    <td><%= retorna_email_aluno(matricula.aluno_id)%></td>
    <td><%= retorna_telefone_aluno(matricula.aluno_id)%></td>
  </tr>

<%end%>  
</table>
    
<% end %>

app/views/disciplinas/checa.html.erb
<h1>Listando disciplinas cadastradas</h1>
<p>A tabela abaixo apresenta as disciplinas cadastradas no banco de dados do sistema de contagem de créditos.</p>
<%= link_to 'Cadastrar disciplina', new_disciplina_path %> </br>
<table>
  <tr>
    <th>Código</th>
    <th>Nome</th>
    <th>Matriz</th>
    <th>Categoria</th>
    <th></th>
    <th></th>
  </tr>

<% @disciplinas.each do |disciplina| %>
  
<% unless disciplina.tipodisciplina_bct == 1 %>
  <tr>
    <td><%= check_box_tag "nome"%></td>
    <td><%= disciplina.codigo_disciplina %></td>
    <td><%= link_to disciplina.nome_disciplina, disciplina %></td>
    <td><%= disciplina.codigo_covalidacao %></td>
    <td><%= link_to disciplina.nome_covalidacao, disciplina %></td>    
    
    <td><%= disciplina.matriz %></td>
    <td><%= disciplina.tipodisciplina_lmat %></td>
   <!-- <td><%= link_to 'Show', disciplina %></td> -->
    <td><%= link_to 'Editar', edit_disciplina_path(disciplina) %></td>
    <td><%= link_to 'Deletar', disciplina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <%end %>
<% end %>
</table>

<br />

app/views/disciplinas/edit.html.erb
<h1>Editar disciplina</h1>
<%= render 'matriculas' %>
<br>
<%= render 'form' %>

<%= link_to 'Mostrar', @disciplina %> |
<%= link_to 'Voltar', disciplinas_path %>

app/views/disciplinas/index.html.erb
<h1><%= @titulo%></h1>
<%= link_to 'Cadastrar Nova Disciplina', new_disciplina_path %>
<table>
  <tr>
    <% if current_usuario.tipo == "Aluno"%>
        <th></th>
    <%end%>
    
 <!--   <th>Curso</th> -->
    <th>Codigo</th>
    <th>Nome</th>
    <th>Turno</th>
    <th>Dia</th>
    <th>Horario de inicio</th>
    <th>Horario de fim</th>
    <th>Docente</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @disciplinas.each do |disciplina| %>
  
<% if filtro_centro(disciplina.id) %>
  <tr>    
 
    <td><%= disciplina.codigo %></td>
    <td><%= disciplina.nome %></td>
    <td><%= disciplina.turno %></td>
    <td><%= disciplina.dia %></td>
    <td><%= I18n.l disciplina.horario_inicio, :format => :hora %></td>
    <td><%= I18n.l disciplina.horario_fim, :format => :hora %></td>
    <td><%= disciplina.docente %></td>
    <td><%= link_to 'Detalhes', disciplina %></td>    
    <td><%= link_to 'Editar', edit_disciplina_path(disciplina) %></td>
    <td><%= link_to 'Deletar', :controller => 'disciplinas', :action => 'delete', :id => disciplina.id %></td>
     
  </tr>
<% end %>  
<% end%>  

</table>

<br />

app/views/disciplinas/new.html.erb
<h1>Nova disciplina</h1>

<%= render 'form' %>

<%= link_to 'Voltar', disciplinas_path %>

app/views/disciplinas/quick.html.erb
<p class="flash-notice"><font color = "red"><%= flash[:notice] %></font></p>

<h1>Contagem de créditos</h1>
<p>Envie para o sistema o arquivo em formato .CSV</p>

<%= form_for(:arquivo, :url => {:controller => 'disciplinas', :action => 'quick2'}) do |p| %>

<%= p.file_field :file %>
<%=p.hidden_field :file_cache %><br><br>


<%= p.submit "enviar"%>
<% end %>

app/views/disciplinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @disciplina.codigo %>
</p>

<p>
  <b>Nome da disciplina:</b>
  <%= @disciplina.nome %>
</p>

<p>
  <b>Curso:</b>
  <%= @disciplina.curso %>
</p>

<p>
  <b>Turno:</b>
  <%= @disciplina.turno %>
</p>

<p>
  <b>Dia:</b>
  <%= @disciplina.dia %>
</p>

<p>
  <b>Horario de inicio:</b>
  <%= I18n.l @disciplina.horario_inicio, :format => :hora %>
</p>

<p>
  <b>Horario de fim:</b>
  <%= I18n.l @disciplina.horario_fim, :format => :hora %>
</p>