config/routes.rb
Estagio::Application.routes.draw do

  

  

scope 'estagios/' do

resources :cancelamentos
resources :aprovas
resources :docentes
resources :fluxomatriculas
      
    devise_for :usuarios, :controllers => { :registrations => "registrations" } do
    get 'logout' => 'sessions#destroy', :as => :destroy_user_session
    get 'login' => 'devise/sessions#new'
  end
      match 'home', :controller => 'avisos', :action => 'home'
      match'/confirm', :controller => 'avisos', :action => 'confirm'

    
      match '/cadastro', :controller => 'matriculas', :action => 'cadastro'
      match '/cadastro/create', :controller => 'matriculas', :action => 'create'
      match '/cadastro/filtro', :controller => 'matriculas', :action => 'filtro'
    
      match '/email/matriculas', :controller => 'matriculas', :action => 'email_matriculas'
      
      match '/matriculas/detalhes/:id', :controller => 'matriculas', :action => 'detalhes'
      match '/matriculas/analise/:id', :controller => 'matriculas', :action => 'analise'
      match '/matriculas/anexo/:id', :controller => 'matriculas', :action => 'anexo'
      match '/matriculas/download/:id', :controller => 'matriculas', :action => 'download'
      
      match '/delete/disciplina/', :controller => 'disciplinas', :action => 'delete'
      match 'delete/aviso', :controller => 'avisos', :action => 'delete'
      match 'delete/periodo', :controller => 'periodos', :action => 'delete'
      
      match 'users/', :controller => 'users', :action => 'index'
      match 'users/edit', :controller => 'users', :action => 'edit'
      match 'users/update/:id', :controller => 'users', :action => 'update'
      match 'user/:id', :controller => 'users', :action => 'show'
      match '/teste',:controller => 'conceitos', :action => 'dssi.xls',:format => 'xls'
      match "relatorios/", :controller => 'relatorios', :action => 'index'
      match "relatorios/show/:id", :controller => 'relatorios', :action => 'show'
      match "relatorios/view/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'view', :format => 'pdf'
      match "relatorios/envio/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'envio'
      match "relatorios/detalhes/:periodo/:aluno_id/", :controller => 'relatorios', :action => 'detalhes'
      match '/testando',:controller=>'relatorios',:action=>'geral',:format=>'pdf'
      match "/cancelamento", :controller => 'cancelamentos', :action => 'inicio'
      match "/cancelamentos/new", :controller => 'cancelamentos', :action => 'show'
	  match "/cancelamentos/testo/:id", :controller=>'cancelamentos', :action=>'edit'
      match "conceitos/", :controller => 'conceitos', :action => 'index'
      match "conceitos/show/:id", :controller => 'conceitos', :action => 'show'
      match "conceitos/envio/:id", :controller => 'conceitos', :action => 'envio'
      match "conceitos/modelo/:curso/:periodo", :controller => 'conceitos', :action => 'modelo_email'      
      match "conceitos/dssi/:periodo/:ci.xls", :controller => 'conceitos', :action => 'dssi', :format => 'xls'
      match "conceitos/relatorio/:curso/:periodo", :controller => 'conceitos', :action => 'relatorio', :format => 'pdf'
      match "te",:controller => 'relatorios', :action => 'geral', :format => 'pdf'
	  match "/aprova", :controller => 'aprovas', :action=> 'index'
      match "/aprova/edit/:id", :controller => 'aprovas', :action=> 'edit'
      match "/aprova/new/:id", :controller => 'aprovas', :action=> 'new'
      
      match "/unificado/envio2/:id",:controller => 'relatorios', :action => 'envio2'
      match "/unificado/:centro/:id",:controller => 'relatorios', :action => 'unificado',:format=>'pdf'
	  
	  match "/dssirelatorio",:controller=>'dssirelatorios',:action=>'index'
      match "/dssirelatorios/:id", :controller=>'dssirelatorios',:action=>'show'
      match "/enviados/:id/:ci", :controller=>'dssirelatorios',:action=>'enviados',:format=>'pdf'
      
      match "/matricula/individual",:controller=>'matriculas',:action=>'individual'
      match "/matricula/individual/relindiv/:id",:controller=>'matriculas',:action=>'relindiv',:format=>'pdf'
      
      match "/docentes",:controller=>'docentes',:action=>'index'
	  
	  match "/fluxo",:controller=>'fluxomatriculas', :action=>'selecionadata'
      match "/fluxo/:periodo_id",:controller=>'fluxomatriculas', :action=>'selecionaaluno'
      match "/fluxo/:periodo_id/:aluno_id",:controller=>'fluxomatriculas', :action=>'fluxo',:format=>'pdf'

  

    	resources :cancelamentos
      resources :disciplinas
      resources :matriculas
      resources :periodos
	  
      
  root :to => 'avisos#index'

    
   resources :avisos
    
  end

end

app/models/cancelamento.rb
class Cancelamento < ActiveRecord::Base
  belongs_to :matricula
  attr_accessible :aluno_id, :disciplina_id, :justificativa, :nomedis, :parecer, :status, :mensagem,:periodo_id,:centro
 validates :justificativa, :presence => true
 
end

app/controllers/cancelamentos_controller.rb
class CancelamentosController < ApplicationController
  # GET /cancelamentos
  # GET /cancelamentos.json


  def index
    @cancelamentos = Cancelamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cancelamentos }
    end
  end

  # GET /cancelamentos/1
  # GET /cancelamentos/1.json
  def show
    @cancelamento = Cancelamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cancelamento }
    end
  end

  # GET /cancelamentos/new
  # GET /cancelamentos/new.json
  def new
    @cancelamento = Cancelamento.new
    @usuario_id=current_usuario.id
    @periodo=Periodo.find(:last)
$disciplinas_aux = Matricula.find(:all,:conditions=>{:periodo_id=>@periodo.id,:aluno_id=>current_usuario.id,:cancelou=> nil})
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cancelamento }
    end
     
  end

  # GET /cancelamentos/1/edit
  def edit
    @cancelamento = Cancelamento.find(params[:id])
   
    @stat=Matricula.find(:first,:conditions=>{:aluno_id=>@cancelamento.aluno_id})
    @stat.update_attributes(:status=>'10',:parecer=>"Matricula Cancelada")
   
  end

  # POST /cancelamentos
  # POST /cancelamentos.json
  def create
    @cancelamento = Cancelamento.new(params[:cancelamento])
    @periodo=Periodo.find(:last)
    @auxi = Disciplina.find(:all, :conditions => {:nome=> @cancelamento.nomedis,:periodo_id=>@periodo.id})
    @auxi.each do |teste|
      $matricula = Matricula.find(:first,:conditions=> {:disciplina_id=>teste.id})
    if $matricula == nil
      puts 'TESTE'
    else 
      $id=$matricula.disciplina_id
    end
    end
    @cancelamento.disciplina_id = $id
   
    @aluno= Usuario.find(:first, :conditions=> {:id=>current_usuario.id})
    @cancelamento.aluno_id = @aluno.id
    if (@cancelamento.nomedis).include?("mat") 
      @cancelamento.update_attributes(:centro=>'CMCC')
    else
      @cancelamento.update_attributes(:centro=>'CCNH')
    end

    @duplicada= Matricula.find(:first,:conditions=> {:disciplina_id=>$id, :aluno_id=>current_usuario.id})
    @duplicada.update_attributes(:cancelou=> 'Solicitou')
    
    respond_to do |format|
      if @cancelamento.save
        format.html { redirect_to @cancelamento, notice: 'Solicitacao criada com sucesso'}
        format.json { render json: @cancelamento, status: :created, location: @cancelamento }
      else
        format.html { render action: "new" }
        format.json { render json: @cancelamento.errors, status: :unprocessable_entity }
      end
    end
    
    CancelamentoMailer.confirma(@aluno,@parecer,@email,@cancelamento).deliver 
        flash[:notice] = t(:confirma)
        
        if current_usuario.centro=="CMCC"
    CancelamentoMailer.aviso(@aluno,@parecer,@email,@cancelamento).deliver 
        flash[:notice] = t(:confirma)
        else
    CancelamentoMailer.aviso1(@aluno,@parecer,@email,@cancelamento).deliver 
        flash[:notice] = t(:confirma)
  end
  
@testando=@cancelamento.aluno_id
    @usuario=Usuario.find(:first, :conditions => {:id=> @testando})
    @parecer = Cancelamento.find(@cancelamento.id)
    @mensagem = Cancelamento.find(@cancelamento.id)
    @disciplina = Cancelamento.find(@cancelamento.id)
    @cancelamento=Cancelamento.find(@cancelamento.id)
    if @cancelamento.parecer == 'Deferido'
    @stat=Matricula.find(:first,:conditions=>{:aluno_id=>@usuario.id})
    @stat.update_attributes(:status=>'10',:parecer=>"Matricula Cancelada")
    end

  end

  # PUT /cancelamentos/1
  # PUT /cancelamentos/1.json
  
  def update
   
    
@cancelamento =Cancelamento.find(params[:id])
  @parecer = Cancelamento.find(:first,:conditions=> {:id=>@cancelamento.id})
    if @parecer.parecer == 'Deferido'
    @stat=Matricula.find(:last,:conditions=>{:aluno_id=>@usuario.id})
    @stat.update_attributes(:status=>'10',:parecer=>"Matricula Cancelada")
    end
    
    respond_to do |format|
      if @cancelamento.update_attributes(params[:cancelamento])
        format.html { redirect_to @cancelamento, notice: 'Avaliacao realizada com sucesso com sucesso'}
        format.json { head :no_content }
      else
        format.html { render action: "editar" }
        format.json { render json: @cancelamento.errors, status: :unprocessable_entity }
      end
    end
    @cancelamento =Cancelamento.find(params[:id])
    @testando=@cancelamento.aluno_id
    @usuario=Usuario.find(:first, :conditions => {:id=> @testando})
    @parecer = Cancelamento.find(:first,:conditions=> {:id=>@cancelamento.id})
    @mensagem = Cancelamento.find(params[:id])
    @disciplina = Cancelamento.find(params[:id])
    @cancelamento=Cancelamento.find(params[:id])
 CancelamentoMailer.resultado(@usuario,@parecer,@disciplina,@mensagem,@nome).deliver 
        flash[:notice] = t(:resultado)
  
  end
  

  # DELETE /cancelamentos/1
  # DELETE /cancelamentos/1.json
  def destroy
    @cancelamento = Cancelamento.find(params[:id])
    @cancelamento.destroy

    respond_to do |format|
      format.html { redirect_to cancelamentos_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/cancelamentos_helper.rb
module CancelamentosHelper
  def parecer
   if @cancelamento.parecer == 'Deferido'
      @cancelamento.status = 10
    end
  end
  def retorna_nome_dis(id)
    @dis=Disciplina.find(:first,:conditions=>{:id=>id})
    @dis.nome
  end
   
end

app/views/cancelamentos/_form.html.erb
<% if current_usuario.tipo=='Aluno' %>
<%= form_for(@cancelamento) do |f| %>
  <% if @cancelamento.errors.any? %>
    <div id="error_explanation">
      <h2>Por favor, corrija os erros abaixo:</h2>

      <ul>
      <% @cancelamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%@periodoatual=Periodo.find(:last)%>
<div class="field">
    <%= f.hidden_field :periodo_id, :value =>@periodoatual.id %>
  </div>


 <div class="field">
    <%= f.label :Nome_da_Disciplina %><br />
    <%= f.select :nomedis, $disciplinas_aux.collect{|m| retorna_nome_dis([m.disciplina_id])}%> 
  </div>


 <div class="field">
    <%= f.label :"Justificativa (*)" %><br />
    
    <%= f.text_field :justificativa %>
  </div>
  <div class="actions">
    <%= f.submit "Avançar" %>
  </div>
<% end %>

<%else%>
<%= form_for(@cancelamento) do |f| %>
  <% if @cancelamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cancelamento.errors.count, "error") %> prohibited this cancelamento from being saved:</h2>

      <ul>
      <% @cancelamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if current_usuario.tipo == "Administrador"%>



<%end%>

 <div class="field">
    <%= f.label :Mensagem_da_Secretaria %><br />
    <%= f.text_field :mensagem %>
  </div>
<div class="field">
    <%= f.label :Justificativa_do_Aluno%><br />
    <%= f.text_area :justificativa %>
  </div>
 <div class="field">
    <%= f.label :Parecer %><br />
    <%= f.select :parecer,[["Deferido"],["Indeferido"]]   %>
  </div>

  <div class="actions">
    <%= f.submit 'Salvar'%>
  </div>
<% end %>

<%end%>

app/views/cancelamentos/edit.html.erb
<h1>Editar solicitação</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @cancelamento %> |
<%= link_to 'Voltar', cancelamento_path %>

app/views/cancelamentos/index.html.erb
<% if current_usuario.tipo == 'Aluno' %>
<h1>Meus cancelamentos</h1>

<p><h10> Para solicitar um cancelamento de matéria, clique no  botão "Nova Solicitação" e <b>digite o nome da disciplina de acordo com sua matricula</b>, <td><%= link_to 'Clique aqui', avisos_path %>, para obter esta informação</td> : </h10></p>
<p> </p>
<table>
  <tr>
    <th>Aluno</th>
    <th>Nome Disciplina</th>
    <th>Justificativa</th>
    <th></th>
    <th></th>
  </tr>


<% @cancelamentos.each do |cancelamento| %>
  <tr>
      <%  if current_usuario.id == cancelamento.aluno_id%>
    <td><%= retorna_nome_aluno(cancelamento.aluno_id) %></td>
    <td><%= (cancelamento.nomedis) %></td>
    <td><%= (cancelamento.justificativa) %></td>
    <td><%= link_to 'Resumo', cancelamento %></td>
    <td><%= link_to 'Editar', edit_cancelamento_path(cancelamento) %></td>
  </tr> 
  <%end%>
<% end %>

</table>

<br />
<%= link_to "Nova Solicitação", :controller=> 'cancelamentos', :action=>'new' %>


 <%else%>
<%  if current_usuario.centro=="CMCC"%>

<h1>Solicitações de cancelamentos</h1>

<table>
  <tr>
    <th>Aluno</th>
    <th>Nome Disciplina</th>
    <th>Mensagem (Secretaria)</th>
    <th>Justificativa (Aluno)</th>
    <th>Parecer</th>
    <th></th>
  </tr>

<%  @cancelar= Cancelamento.find(:all,:conditions=>{:periodo_id=>params[:id],:centro=>'CMCC'})%>
<% @cancelar.each do |cancelar| %>
 
  <%@turno=Disciplina.find(:first,:conditions=>{:id=>cancelar.disciplina_id})%>
   <%@data=Periodo.find(params[:id])%>
  
  <tr>
    <td><%= link_to retorna_nome_aluno(cancelar.aluno_id), cancelar  %></td> 
    <td><%= retorna_nome_disciplina (cancelar.disciplina_id) %></td>
    <td><%= cancelar.mensagem %></td>
    <td><%= cancelar.justificativa %></td>
    <td><%= cancelar.parecer %></td>
    <%if cancelar.parecer == nil%>
    <td><%= link_to 'Avaliar', "/estagios/cancelamentos/testo/"+cancelar.id.to_s%></td>
    <% else %>
    <td><%= "Avaliação já realizada"  %></td>
    <%end%>
  </tr>

<% end %>

</table>

<br />


<%else%>
<h1>Solicitações de cancelamentos</h1>

<table>
  <tr>
    <th>Aluno</th>
    <th>Nome Disciplina</th>
    <th>Mensagem (Secretaria)</th>
    <th>Justificativa (Aluno)</th>
    <th>Parecer</th>
    <th></th>
  </tr>

<%  @cancelar= Cancelamento.find(:all,:conditions=>{:periodo_id=>params[:id],:centro=>'CCNH'})%>
<% @cancelar.each do |cancelar| %>
 
  <%@turno=Disciplina.find(:first,:conditions=>{:id=>cancelar.disciplina_id})%>
   <%@data=Periodo.find(params[:id])%>
  
  <tr>
    <td><%= link_to retorna_nome_aluno(cancelar.aluno_id), cancelar  %></td> 
    <td><%= retorna_nome_disciplina (cancelar.disciplina_id) %></td>
    <td><%= cancelar.mensagem %></td>
    <td><%= cancelar.justificativa %></td>
    <td><%= cancelar.parecer %></td>
    <%if cancelar.parecer == nil%>
    <td><%= link_to 'Avaliar', edit_cancelamento_path(cancelar) %></td>
    <% else %>
    <td><%= "Avaliação já realizada"  %></td>
    <%end%>
  </tr>

<% end %>

</table>

<br />

<%end%>
<%end%>

app/views/cancelamentos/inicio.erb
<h1>Períodos cadastrados</h1>
<p>Selecione o período que deseja gerar os relatórios:</p>

<table>
  <tr>
    <th>Quadrimestre</th>
    <th>Ano</th>
    <th></th>
  </tr>
<%@periodos=Periodo.find(:all,:order => "ano ASC" )%>
<% @periodos = @periodos.reverse!%>
<% @periodos.each do |periodo| %>
  <tr>
    <td><%= periodo.quadrimestre %></td>
    <td><%= periodo.ano %></td>
    <td><%= link_to 'Avançar', :controller => 'cancelamentos', :action => 'index', :id => periodo.id %></td> 
    
  </tr>
<% end %>
</table>

<br />

app/views/cancelamentos/new.html.erb
<h1>Solicitar Cancelamento</h1>
<h><b><p style="color:green"> Os campos marcados com (*) são de preenchimento obrigatório </b></p></h>
</p>
<%= render 'form' %>

<%= link_to 'Voltar', cancelamentos_path %>

app/views/cancelamentos/show.html.erb
<p id="notice"><%= notice %></p>
<%@turno=Disciplina.find(:first,:conditions=>{:id=>@cancelamento.disciplina_id})%>
   <%@data=Periodo.find(:first,:conditions=>{:id=>@turno.periodo_id})%>
<p>
  <b>Aluno:</b>
  <%= retorna_nome_aluno(@cancelamento.aluno_id) %>
</p>
<p>
  <b>Disciplina:</b>
  <%= retorna_nome_disciplina(@cancelamento.disciplina_id) %>
</p>

<p>
  <b>Justificativa:</b>
  <%= @cancelamento.justificativa %>
</p>

<p>
  <b>Quadrimestre:</b>
  <%= @data.quadrimestre %>
</p>
<p>
  <b>Turno:</b>
  <%= @turno.turno %>
</p>

<p><%= link_to 'Reavaliar', edit_cancelamento_path(@cancelamento) %> </p>

<p><%= link_to 'Voltar', '/estagios/cancelamento' %></p>