config/routes.rb
Estagio::Application.routes.draw do

  

  

scope 'estagios/' do

resources :cancelamentos
resources :aprovas
resources :docentes
resources :fluxomatriculas
      
    devise_for :usuarios, :controllers => { :registrations => "registrations" } do
    get 'logout' => 'sessions#destroy', :as => :destroy_user_session
    get 'login' => 'devise/sessions#new'
  end
      match 'home', :controller => 'avisos', :action => 'home'
      match'/confirm', :controller => 'avisos', :action => 'confirm'

    
      match '/cadastro', :controller => 'matriculas', :action => 'cadastro'
      match '/cadastro/create', :controller => 'matriculas', :action => 'create'
      match '/cadastro/filtro', :controller => 'matriculas', :action => 'filtro'
    
      match '/email/matriculas', :controller => 'matriculas', :action => 'email_matriculas'
      
      match '/matriculas/detalhes/:id', :controller => 'matriculas', :action => 'detalhes'
      match '/matriculas/analise/:id', :controller => 'matriculas', :action => 'analise'
      match '/matriculas/anexo/:id', :controller => 'matriculas', :action => 'anexo'
      match '/matriculas/download/:id', :controller => 'matriculas', :action => 'download'
      
      match '/delete/disciplina/', :controller => 'disciplinas', :action => 'delete'
      match 'delete/aviso', :controller => 'avisos', :action => 'delete'
      match 'delete/periodo', :controller => 'periodos', :action => 'delete'
      
      match 'users/', :controller => 'users', :action => 'index'
      match 'users/edit', :controller => 'users', :action => 'edit'
      match 'users/update/:id', :controller => 'users', :action => 'update'
      match 'user/:id', :controller => 'users', :action => 'show'
      match '/teste',:controller => 'conceitos', :action => 'dssi.xls',:format => 'xls'
      match "relatorios/", :controller => 'relatorios', :action => 'index'
      match "relatorios/show/:id", :controller => 'relatorios', :action => 'show'
      match "relatorios/view/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'view', :format => 'pdf'
      match "relatorios/envio/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'envio'
      match "relatorios/detalhes/:periodo/:aluno_id/", :controller => 'relatorios', :action => 'detalhes'
      match '/testando',:controller=>'relatorios',:action=>'geral',:format=>'pdf'
      match "/cancelamento", :controller => 'cancelamentos', :action => 'inicio'
      match "/cancelamentos/new", :controller => 'cancelamentos', :action => 'show'
	  match "/cancelamentos/testo/:id", :controller=>'cancelamentos', :action=>'edit'
      match "conceitos/", :controller => 'conceitos', :action => 'index'
      match "conceitos/show/:id", :controller => 'conceitos', :action => 'show'
      match "conceitos/envio/:id", :controller => 'conceitos', :action => 'envio'
      match "conceitos/modelo/:curso/:periodo", :controller => 'conceitos', :action => 'modelo_email'      
      match "conceitos/dssi/:periodo/:ci.xls", :controller => 'conceitos', :action => 'dssi', :format => 'xls'
      match "conceitos/relatorio/:curso/:periodo", :controller => 'conceitos', :action => 'relatorio', :format => 'pdf'
      match "te",:controller => 'relatorios', :action => 'geral', :format => 'pdf'
	  match "/aprova", :controller => 'aprovas', :action=> 'index'
      match "/aprova/edit/:id", :controller => 'aprovas', :action=> 'edit'
      match "/aprova/new/:id", :controller => 'aprovas', :action=> 'new'
      
      match "/unificado/envio2/:id",:controller => 'relatorios', :action => 'envio2'
      match "/unificado/:centro/:id",:controller => 'relatorios', :action => 'unificado',:format=>'pdf'
	  
	  match "/dssirelatorio",:controller=>'dssirelatorios',:action=>'index'
      match "/dssirelatorios/:id", :controller=>'dssirelatorios',:action=>'show'
      match "/enviados/:id/:ci", :controller=>'dssirelatorios',:action=>'enviados',:format=>'pdf'
      
      match "/matricula/individual",:controller=>'matriculas',:action=>'individual'
      match "/matricula/individual/relindiv/:id",:controller=>'matriculas',:action=>'relindiv',:format=>'pdf'
      
      match "/docentes",:controller=>'docentes',:action=>'index'
	  
	  match "/fluxo",:controller=>'fluxomatriculas', :action=>'selecionadata'
      match "/fluxo/:periodo_id",:controller=>'fluxomatriculas', :action=>'selecionaaluno'
      match "/fluxo/:periodo_id/:aluno_id",:controller=>'fluxomatriculas', :action=>'fluxo',:format=>'pdf'

  

    	resources :cancelamentos
      resources :disciplinas
      resources :matriculas
      resources :periodos
	  
      
  root :to => 'avisos#index'

    
   resources :avisos
    
  end

end

app/models/docente.rb
class Docente < ActiveRecord::Base
  attr_accessible :centro, :docente, :email, :ramal
  validates_format_of :email, :with => /\A([^@\s]+)@(aluno\.ufabc\.edu\.br)|(ufabc\.edu\.br)\z/
  validates :docente, :presence => true
  validates :email, :uniqueness => true
end

app/controllers/docentes_controller.rb
class DocentesController < ApplicationController
  # GET /docentes
  # GET /docentes.json
  def index
    @docentes = Docente.find(:all,:conditions=>{:centro=>current_usuario.centro},:order=>'docente')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @docentes }
    end
  end

  # GET /docentes/1
  # GET /docentes/1.json
  def show
    @docente = Docente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @docente }
    end
  end

  # GET /docentes/new
  # GET /docentes/new.json
  def new
    @docente = Docente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @docente }
    end
  end

  # GET /docentes/1/edit
  def edit
    @docente = Docente.find(params[:id])
  end

  # POST /docentes
  # POST /docentes.json
  def create
    @docente = Docente.new(params[:docente])

    respond_to do |format|
      if @docente.save
        format.html { redirect_to @docente, notice: 'Docente was successfully created.' }
        format.json { render json: @docente, status: :created, location: @docente }
      else
        format.html { render action: "new" }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /docentes/1
  # PUT /docentes/1.json
  def update
    @docente = Docente.find(params[:id])

    respond_to do |format|
      if @docente.update_attributes(params[:docente])
        format.html { redirect_to @docente, notice: 'Docente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docentes/1
  # DELETE /docentes/1.json
  def destroy
    @docente = Docente.find(params[:id])
    @docente.destroy

    respond_to do |format|
      format.html { redirect_to docentes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/docentes_helper.rb
module DocentesHelper
end

app/views/docentes/_form.html.erb
<%= form_for(@docente) do |f| %>
  <% if @docente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@docente.errors.count, "error") %> prohibited this docente from being saved:</h2>

      <ul>
      <% @docente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :docente %><br />
    <%= f.text_field :docente %>
  </div>
  <div class="field">
    <%= f.label :centro %><br />
    <%= f.select :centro, [["CMCC"],["CCNH"]] %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :ramal %><br />
    <%= f.text_field :ramal %>
  </div>
  <div class="actions">
    <%= f.submit "Cadastrar" %>
  </div>
<% end %>

app/views/docentes/edit.html.erb
<h1>Editing docente</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @docente %> |
<%= link_to 'Voltar', docentes_path %>

app/views/docentes/index.html.erb
<h1>Docentes Cadastrados</h1>

<table>
  <tr>
    <th>Docente</th>
    <th>Centro</th>
    <th>Email</th>
    <th>Ramal</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @docentes.each do |docente| %>
  <tr>
    <td><%= docente.docente %></td>
    <td><%= docente.centro %></td>
    <td><%= docente.email %></td>
    <td><%= docente.ramal %></td>
    <td><%= link_to 'Visualizar', docente %></td>
    <td><%= link_to 'Editar', edit_docente_path(docente) %></td>
    <td><%= link_to 'Excluir', docente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Cadastar Docente', new_docente_path %>

app/views/docentes/new.html.erb
<h1>Novo cadastro</h1>

<%= render 'form' %>

<%= link_to 'Voltar', docentes_path %>

app/views/docentes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Docente:</b>
  <%= @docente.docente %>
</p>

<p>
  <b>Centro:</b>
  <%= @docente.centro %>
</p>

<p>
  <b>Email:</b>
  <%= @docente.email %>
</p>

<p>
  <b>Ramal:</b>
  <%= @docente.ramal %>
</p>


<%= link_to 'Editar', edit_docente_path(@docente) %> |
<%= link_to 'Voltar', docentes_path %>