config/routes.rb
Estagio::Application.routes.draw do

  

  

scope 'estagios/' do

resources :cancelamentos
resources :aprovas
resources :docentes
resources :fluxomatriculas
      
    devise_for :usuarios, :controllers => { :registrations => "registrations" } do
    get 'logout' => 'sessions#destroy', :as => :destroy_user_session
    get 'login' => 'devise/sessions#new'
  end
      match 'home', :controller => 'avisos', :action => 'home'
      match'/confirm', :controller => 'avisos', :action => 'confirm'

    
      match '/cadastro', :controller => 'matriculas', :action => 'cadastro'
      match '/cadastro/create', :controller => 'matriculas', :action => 'create'
      match '/cadastro/filtro', :controller => 'matriculas', :action => 'filtro'
    
      match '/email/matriculas', :controller => 'matriculas', :action => 'email_matriculas'
      
      match '/matriculas/detalhes/:id', :controller => 'matriculas', :action => 'detalhes'
      match '/matriculas/analise/:id', :controller => 'matriculas', :action => 'analise'
      match '/matriculas/anexo/:id', :controller => 'matriculas', :action => 'anexo'
      match '/matriculas/download/:id', :controller => 'matriculas', :action => 'download'
      
      match '/delete/disciplina/', :controller => 'disciplinas', :action => 'delete'
      match 'delete/aviso', :controller => 'avisos', :action => 'delete'
      match 'delete/periodo', :controller => 'periodos', :action => 'delete'
      
      match 'users/', :controller => 'users', :action => 'index'
      match 'users/edit', :controller => 'users', :action => 'edit'
      match 'users/update/:id', :controller => 'users', :action => 'update'
      match 'user/:id', :controller => 'users', :action => 'show'
      match '/teste',:controller => 'conceitos', :action => 'dssi.xls',:format => 'xls'
      match "relatorios/", :controller => 'relatorios', :action => 'index'
      match "relatorios/show/:id", :controller => 'relatorios', :action => 'show'
      match "relatorios/view/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'view', :format => 'pdf'
      match "relatorios/envio/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'envio'
      match "relatorios/detalhes/:periodo/:aluno_id/", :controller => 'relatorios', :action => 'detalhes'
      match '/testando',:controller=>'relatorios',:action=>'geral',:format=>'pdf'
      match "/cancelamento", :controller => 'cancelamentos', :action => 'inicio'
      match "/cancelamentos/new", :controller => 'cancelamentos', :action => 'show'
	  match "/cancelamentos/testo/:id", :controller=>'cancelamentos', :action=>'edit'
      match "conceitos/", :controller => 'conceitos', :action => 'index'
      match "conceitos/show/:id", :controller => 'conceitos', :action => 'show'
      match "conceitos/envio/:id", :controller => 'conceitos', :action => 'envio'
      match "conceitos/modelo/:curso/:periodo", :controller => 'conceitos', :action => 'modelo_email'      
      match "conceitos/dssi/:periodo/:ci.xls", :controller => 'conceitos', :action => 'dssi', :format => 'xls'
      match "conceitos/relatorio/:curso/:periodo", :controller => 'conceitos', :action => 'relatorio', :format => 'pdf'
      match "te",:controller => 'relatorios', :action => 'geral', :format => 'pdf'
	  match "/aprova", :controller => 'aprovas', :action=> 'index'
      match "/aprova/edit/:id", :controller => 'aprovas', :action=> 'edit'
      match "/aprova/new/:id", :controller => 'aprovas', :action=> 'new'
      
      match "/unificado/envio2/:id",:controller => 'relatorios', :action => 'envio2'
      match "/unificado/:centro/:id",:controller => 'relatorios', :action => 'unificado',:format=>'pdf'
	  
	  match "/dssirelatorio",:controller=>'dssirelatorios',:action=>'index'
      match "/dssirelatorios/:id", :controller=>'dssirelatorios',:action=>'show'
      match "/enviados/:id/:ci", :controller=>'dssirelatorios',:action=>'enviados',:format=>'pdf'
      
      match "/matricula/individual",:controller=>'matriculas',:action=>'individual'
      match "/matricula/individual/relindiv/:id",:controller=>'matriculas',:action=>'relindiv',:format=>'pdf'
      
      match "/docentes",:controller=>'docentes',:action=>'index'
	  
	  match "/fluxo",:controller=>'fluxomatriculas', :action=>'selecionadata'
      match "/fluxo/:periodo_id",:controller=>'fluxomatriculas', :action=>'selecionaaluno'
      match "/fluxo/:periodo_id/:aluno_id",:controller=>'fluxomatriculas', :action=>'fluxo',:format=>'pdf'

  

    	resources :cancelamentos
      resources :disciplinas
      resources :matriculas
      resources :periodos
	  
      
  root :to => 'avisos#index'

    
   resources :avisos
    
  end

end

app/models/fluxomatricula.rb
class Fluxomatricula < ActiveRecord::Base
  attr_accessible :aluno_id, :data, :disciplina_id, :periodo_id
end

app/controllers/fluxomatriculas_controller.rb
class FluxomatriculasController < ApplicationController
  # GET /fluxomatriculas
  # GET /fluxomatriculas.json
  def index
    @fluxomatriculas = Fluxomatricula.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fluxomatriculas }
    end
  end

  # GET /fluxomatriculas/1
  # GET /fluxomatriculas/1.json
  def show
    @fluxomatricula = Fluxomatricula.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fluxomatricula }
    end
  end

  # GET /fluxomatriculas/new
  # GET /fluxomatriculas/new.json
  def new
    @fluxomatricula = Fluxomatricula.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fluxomatricula }
    end
  end

  # GET /fluxomatriculas/1/edit
  def edit
    @fluxomatricula = Fluxomatricula.find(params[:id])
  end

  # POST /fluxomatriculas
  # POST /fluxomatriculas.json
  def create
    @fluxomatricula = Fluxomatricula.new(params[:fluxomatricula])

    respond_to do |format|
      if @fluxomatricula.save
        format.html { redirect_to @fluxomatricula, notice: 'Fluxomatricula was successfully created.' }
        format.json { render json: @fluxomatricula, status: :created, location: @fluxomatricula }
      else
        format.html { render action: "new" }
        format.json { render json: @fluxomatricula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fluxomatriculas/1
  # PUT /fluxomatriculas/1.json
  def update
    @fluxomatricula = Fluxomatricula.find(params[:id])

    respond_to do |format|
      if @fluxomatricula.update_attributes(params[:fluxomatricula])
        format.html { redirect_to @fluxomatricula, notice: 'Fluxomatricula was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fluxomatricula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fluxomatriculas/1
  # DELETE /fluxomatriculas/1.json
  def destroy
    @fluxomatricula = Fluxomatricula.find(params[:id])
    @fluxomatricula.destroy

    respond_to do |format|
      format.html { redirect_to fluxomatriculas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fluxomatriculas_helper.rb
module FluxomatriculasHelper
  def retorna_nome(aluno_id)
    @aluno= Usuario.find_by_id(aluno_id)
    @aluno.nome
  end
end

app/views/fluxomatriculas/_form.html.erb
<%= form_for(@fluxomatricula) do |f| %>
  <% if @fluxomatricula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fluxomatricula.errors.count, "error") %> prohibited this fluxomatricula from being saved:</h2>

      <ul>
      <% @fluxomatricula.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aluno_id %><br />
    <%= f.text_field :aluno_id %>
  </div>
  <div class="field">
    <%= f.label :periodo_id %><br />
    <%= f.text_field :periodo_id %>
  </div>
  <div class="field">
    <%= f.label :disciplina_id %><br />
    <%= f.text_field :disciplina_id %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fluxomatriculas/edit.html.erb
<h1>Editing fluxomatricula</h1>

<%= render 'form' %>

<%= link_to 'Show', @fluxomatricula %> |
<%= link_to 'Back', fluxomatriculas_path %>

app/views/fluxomatriculas/index.html.erb
<h1>Listing fluxomatriculas</h1>

<table>
  <tr>
    <th>Aluno</th>
    <th>Periodo</th>
    <th>Disciplina</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fluxomatriculas.each do |fluxomatricula| %>
  <tr>
    <td><%= fluxomatricula.aluno_id %></td>
    <td><%= fluxomatricula.periodo_id %></td>
    <td><%= fluxomatricula.disciplina_id %></td>
    <td><%= fluxomatricula.data %></td>
    <td><%= link_to 'Show', fluxomatricula %></td>
    <td><%= link_to 'Edit', edit_fluxomatricula_path(fluxomatricula) %></td>
    <td><%= link_to 'Destroy', fluxomatricula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fluxomatricula', new_fluxomatricula_path %>

app/views/fluxomatriculas/new.html.erb
<h1>New fluxomatricula</h1>

<%= render 'form' %>

<%= link_to 'Back', fluxomatriculas_path %>

app/views/fluxomatriculas/selecionaaluno.html.erb
<h1>Seleciona o Aluno</h1>

<table>
  <tr>
    <th>Aluno</th>
    <th>RA</th>
    <th></th>
  </tr>
<% @teste=Array.new %>
  <% @fluxomatriculas=Fluxomatricula.find(:all,:conditions=>{:periodo_id=>params[:periodo_id]}) %>
   <% @teste=Array.new %>
<% @fluxomatriculas.each do |fluxomatricula| %>
  <tr>
     <%@teste.append(fluxomatricula.aluno_id)%>
      <%end%>
   <% (@teste.uniq).each do |teste| %>
  <tr>
    <td><%= retorna_nome(teste) %></td>
    <td><%= retorna_ra(teste)%></td>
    <td><%= link_to 'Avançar', "/estagios/fluxo/"+(params[:periodo_id]).to_s+"/"+(teste) %></td>
   
  </tr>
<% end %>
</table>
<br />

app/views/fluxomatriculas/selecionadata.html.erb
<h1>Selecione o Periodo</h1>

<table>
  <tr>
    <th>Quadrimestre</th>
    <th>Ano</th>
    <th></th>
  </tr>
<% @periodos = Periodo.find(:all) %>
<% @periodos = @periodos.reverse!%>
<% @periodos.each do |periodo| %>
  <tr>
    <td><%= periodo.quadrimestre %></td>
    <td><%= periodo.ano%></td>
    <td><%= link_to 'Avançar', "/estagios/fluxo/"+(periodo.id).to_s %></td>
  </tr>
<% end %>
</table>

<br />

app/views/fluxomatriculas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Aluno:</b>
  <%= @fluxomatricula.aluno_id %>
</p>

<p>
  <b>Periodo:</b>
  <%= @fluxomatricula.periodo_id %>
</p>

<p>
  <b>Disciplina:</b>
  <%= @fluxomatricula.disciplina_id %>
</p>

<p>
  <b>Data:</b>
  <%= @fluxomatricula.data %>
</p>


<%= link_to 'Edit', edit_fluxomatricula_path(@fluxomatricula) %> |
<%= link_to 'Back', fluxomatriculas_path %>